# Generated by Django 3.2.9 on 2021-11-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Дата добавления')),
                ('name', models.CharField(max_length=64, verbose_name='Название товара')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена')),
                ('unit', models.CharField(max_length=64, verbose_name='Единица измерения')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Колличество')),
                ('supplier_name', models.CharField(max_length=64, verbose_name='Имя поставщика')),
            ],
        ),
    ]
