# Generated by Django 3.2.9 on 2021-11-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Категория товара')),
            ],
            options={
                'verbose_name_plural': 'Категория товара',
            },
        ),
        migrations.AlterModelOptions(
            name='productlist',
            options={'verbose_name_plural': 'Список товаров'},
        ),
    ]
