# Generated by Django 3.2.9 on 2021-11-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20211127_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlist',
            name='category',
            field=models.ManyToManyField(to='mainapp.ProductCategory', verbose_name='Категория товара'),
        ),
    ]
