# Generated by Django 3.2.9 on 2021-12-14 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('mainapp', '0003_productlist_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='Сайты'),
        ),
        migrations.AddField(
            model_name='productlist',
            name='site',
            field=models.ManyToManyField(null=True, to='sites.Site', verbose_name='Сайты'),
        ),
    ]
