# Generated by Django 3.2.9 on 2021-12-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('mainapp', '0004_auto_20211214_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='site',
            field=models.ManyToManyField(to='sites.Site', verbose_name='Сайты'),
        ),
    ]
